import { nanoid } from "nanoid";
import { sql } from "@/lib/db/client";

/**
 * A reader's own conversations, kept so they survive the tab closing.
 *
 * Threads used to live in localStorage, which was the right call when the
 * alternative was query_log — a table recording every question and answer that
 * nobody could see or clear. It is the wrong call for history: localStorage is
 * gone when the browser clears site data, which happens routinely and without
 * warning, and it cannot hold more than the one thread it was overwriting.
 *
 * So conversations move to the database, scoped to the same owner id the
 * documents use. That is the distinction worth being precise about: the
 * objection to query_log was never that text was stored, it was that the person
 * who wrote it could not see it, list it, or delete it. These they can do all
 * three.
 *
 * It is still not authentication. Anyone holding the cookie is that owner, and
 * clearing cookies loses the history along with the documents.
 */

export interface ConversationSummary {
  id: string;
  title: string;
  turns: number;
  updatedAt: string;
}

/** Enough to be a list, not enough to be a payload: messages are left behind. */
export async function listConversations(ownerId: string): Promise<ConversationSummary[]> {
  const rows = await sql<{ id: string; title: string; turns: number; updated_at: Date }[]>`
    SELECT id, title,
           jsonb_array_length(messages)::int AS turns,
           updated_at
    FROM conversations
    WHERE owner_id = ${ownerId}
    ORDER BY updated_at DESC
    LIMIT 100
  `;
  return rows.map((r) => ({
    id: r.id,
    title: r.title,
    turns: r.turns,
    updatedAt: r.updated_at.toISOString(),
  }));
}

export async function loadConversation(id: string, ownerId: string): Promise<unknown[] | null> {
  const [row] = await sql<{ messages: unknown[] }[]>`
    SELECT messages FROM conversations WHERE id = ${id} AND owner_id = ${ownerId}
  `;
  return row?.messages ?? null;
}

/**
 * The first thing asked, which is what a reader recognises a thread by.
 *
 * Not generated by a model: naming a conversation is not worth a round trip on
 * a provider that serialises them, and a title that paraphrases the question is
 * harder to scan than the question itself.
 */
function titleFrom(messages: { role?: string; parts?: { type?: string; text?: string }[] }[]): string {
  const first = messages.find((m) => m.role === "user");
  const text = (first?.parts ?? [])
    .filter((p) => p.type === "text")
    .map((p) => p.text ?? "")
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
  if (!text) return "Untitled conversation";
  return text.length > 70 ? `${text.slice(0, 70).trimEnd()}…` : text;
}

/** Upserts, returning the id so a new conversation keeps the same row after. */
export async function saveConversation(args: {
  id: string | null;
  ownerId: string;
  messages: { role?: string; parts?: { type?: string; text?: string }[] }[];
}): Promise<{ id: string; title: string }> {
  const title = titleFrom(args.messages);
  const payload = sql.json(args.messages as never);

  if (args.id) {
    const [updated] = await sql<{ id: string }[]>`
      UPDATE conversations
      SET messages = ${payload}, title = ${title}, updated_at = now()
      WHERE id = ${args.id} AND owner_id = ${args.ownerId}
      RETURNING id
    `;
    // An id that is not this owner's updates nothing. Falling through to an
    // insert would otherwise let a guessed id create a row under a title of
    // someone else's choosing.
    if (updated) return { id: updated.id, title };
  }

  const id = nanoid(12);
  await sql`
    INSERT INTO conversations (id, owner_id, title, messages)
    VALUES (${id}, ${args.ownerId}, ${title}, ${payload})
  `;
  return { id, title };
}

export async function deleteConversation(id: string, ownerId: string): Promise<void> {
  await sql`DELETE FROM conversations WHERE id = ${id} AND owner_id = ${ownerId}`;
}
